// Datos de país/código de marcación para el selector de login por teléfono
// (auth-ui.js). Solo name/iso2/dial se mantienen a mano — la bandera se
// deriva de iso2 vía símbolos Unicode regional-indicator (flagEmoji), así
// no hay ~190 emoji tecleados a mano que puedan estar mal.
export const COUNTRY_CODES = [
  { name: 'México', iso2: 'MX', dial: '+52' },
  { name: 'Afganistán', iso2: 'AF', dial: '+93' },
  { name: 'Albania', iso2: 'AL', dial: '+355' },
  { name: 'Alemania', iso2: 'DE', dial: '+49' },
  { name: 'Andorra', iso2: 'AD', dial: '+376' },
  { name: 'Angola', iso2: 'AO', dial: '+244' },
  { name: 'Antigua y Barbuda', iso2: 'AG', dial: '+1268' },
  { name: 'Arabia Saudita', iso2: 'SA', dial: '+966' },
  { name: 'Argelia', iso2: 'DZ', dial: '+213' },
  { name: 'Argentina', iso2: 'AR', dial: '+54' },
  { name: 'Armenia', iso2: 'AM', dial: '+374' },
  { name: 'Australia', iso2: 'AU', dial: '+61' },
  { name: 'Austria', iso2: 'AT', dial: '+43' },
  { name: 'Azerbaiyán', iso2: 'AZ', dial: '+994' },
  { name: 'Bahamas', iso2: 'BS', dial: '+1242' },
  { name: 'Bangladés', iso2: 'BD', dial: '+880' },
  { name: 'Barbados', iso2: 'BB', dial: '+1246' },
  { name: 'Baréin', iso2: 'BH', dial: '+973' },
  { name: 'Bélgica', iso2: 'BE', dial: '+32' },
  { name: 'Belice', iso2: 'BZ', dial: '+501' },
  { name: 'Benín', iso2: 'BJ', dial: '+229' },
  { name: 'Bielorrusia', iso2: 'BY', dial: '+375' },
  { name: 'Birmania (Myanmar)', iso2: 'MM', dial: '+95' },
  { name: 'Bolivia', iso2: 'BO', dial: '+591' },
  { name: 'Bosnia y Herzegovina', iso2: 'BA', dial: '+387' },
  { name: 'Botsuana', iso2: 'BW', dial: '+267' },
  { name: 'Brasil', iso2: 'BR', dial: '+55' },
  { name: 'Brunéi', iso2: 'BN', dial: '+673' },
  { name: 'Bulgaria', iso2: 'BG', dial: '+359' },
  { name: 'Burkina Faso', iso2: 'BF', dial: '+226' },
  { name: 'Burundi', iso2: 'BI', dial: '+257' },
  { name: 'Bután', iso2: 'BT', dial: '+975' },
  { name: 'Cabo Verde', iso2: 'CV', dial: '+238' },
  { name: 'Camboya', iso2: 'KH', dial: '+855' },
  { name: 'Camerún', iso2: 'CM', dial: '+237' },
  { name: 'Canadá', iso2: 'CA', dial: '+1' },
  { name: 'Catar', iso2: 'QA', dial: '+974' },
  { name: 'Chad', iso2: 'TD', dial: '+235' },
  { name: 'Chile', iso2: 'CL', dial: '+56' },
  { name: 'China', iso2: 'CN', dial: '+86' },
  { name: 'Chipre', iso2: 'CY', dial: '+357' },
  { name: 'Ciudad del Vaticano', iso2: 'VA', dial: '+379' },
  { name: 'Colombia', iso2: 'CO', dial: '+57' },
  { name: 'Comoras', iso2: 'KM', dial: '+269' },
  { name: 'Corea del Norte', iso2: 'KP', dial: '+850' },
  { name: 'Corea del Sur', iso2: 'KR', dial: '+82' },
  { name: 'Costa de Marfil', iso2: 'CI', dial: '+225' },
  { name: 'Costa Rica', iso2: 'CR', dial: '+506' },
  { name: 'Croacia', iso2: 'HR', dial: '+385' },
  { name: 'Cuba', iso2: 'CU', dial: '+53' },
  { name: 'Dinamarca', iso2: 'DK', dial: '+45' },
  { name: 'Dominica', iso2: 'DM', dial: '+1767' },
  { name: 'Ecuador', iso2: 'EC', dial: '+593' },
  { name: 'Egipto', iso2: 'EG', dial: '+20' },
  { name: 'El Salvador', iso2: 'SV', dial: '+503' },
  { name: 'Emiratos Árabes Unidos', iso2: 'AE', dial: '+971' },
  { name: 'Eritrea', iso2: 'ER', dial: '+291' },
  { name: 'Eslovaquia', iso2: 'SK', dial: '+421' },
  { name: 'Eslovenia', iso2: 'SI', dial: '+386' },
  { name: 'España', iso2: 'ES', dial: '+34' },
  { name: 'Estados Unidos', iso2: 'US', dial: '+1' },
  { name: 'Estonia', iso2: 'EE', dial: '+372' },
  { name: 'Esuatini (Suazilandia)', iso2: 'SZ', dial: '+268' },
  { name: 'Etiopía', iso2: 'ET', dial: '+251' },
  { name: 'Filipinas', iso2: 'PH', dial: '+63' },
  { name: 'Finlandia', iso2: 'FI', dial: '+358' },
  { name: 'Fiyi', iso2: 'FJ', dial: '+679' },
  { name: 'Francia', iso2: 'FR', dial: '+33' },
  { name: 'Gabón', iso2: 'GA', dial: '+241' },
  { name: 'Gambia', iso2: 'GM', dial: '+220' },
  { name: 'Georgia', iso2: 'GE', dial: '+995' },
  { name: 'Ghana', iso2: 'GH', dial: '+233' },
  { name: 'Granada', iso2: 'GD', dial: '+1473' },
  { name: 'Grecia', iso2: 'GR', dial: '+30' },
  { name: 'Guatemala', iso2: 'GT', dial: '+502' },
  { name: 'Guinea', iso2: 'GN', dial: '+224' },
  { name: 'Guinea Ecuatorial', iso2: 'GQ', dial: '+240' },
  { name: 'Guinea-Bisáu', iso2: 'GW', dial: '+245' },
  { name: 'Guyana', iso2: 'GY', dial: '+592' },
  { name: 'Haití', iso2: 'HT', dial: '+509' },
  { name: 'Honduras', iso2: 'HN', dial: '+504' },
  { name: 'Hungría', iso2: 'HU', dial: '+36' },
  { name: 'India', iso2: 'IN', dial: '+91' },
  { name: 'Indonesia', iso2: 'ID', dial: '+62' },
  { name: 'Irak', iso2: 'IQ', dial: '+964' },
  { name: 'Irán', iso2: 'IR', dial: '+98' },
  { name: 'Irlanda', iso2: 'IE', dial: '+353' },
  { name: 'Islandia', iso2: 'IS', dial: '+354' },
  { name: 'Islas Marshall', iso2: 'MH', dial: '+692' },
  { name: 'Islas Salomón', iso2: 'SB', dial: '+677' },
  { name: 'Israel', iso2: 'IL', dial: '+972' },
  { name: 'Italia', iso2: 'IT', dial: '+39' },
  { name: 'Jamaica', iso2: 'JM', dial: '+1876' },
  { name: 'Japón', iso2: 'JP', dial: '+81' },
  { name: 'Jordania', iso2: 'JO', dial: '+962' },
  { name: 'Kazajistán', iso2: 'KZ', dial: '+7' },
  { name: 'Kenia', iso2: 'KE', dial: '+254' },
  { name: 'Kirguistán', iso2: 'KG', dial: '+996' },
  { name: 'Kiribati', iso2: 'KI', dial: '+686' },
  { name: 'Kuwait', iso2: 'KW', dial: '+965' },
  { name: 'Laos', iso2: 'LA', dial: '+856' },
  { name: 'Lesoto', iso2: 'LS', dial: '+266' },
  { name: 'Letonia', iso2: 'LV', dial: '+371' },
  { name: 'Líbano', iso2: 'LB', dial: '+961' },
  { name: 'Liberia', iso2: 'LR', dial: '+231' },
  { name: 'Libia', iso2: 'LY', dial: '+218' },
  { name: 'Liechtenstein', iso2: 'LI', dial: '+423' },
  { name: 'Lituania', iso2: 'LT', dial: '+370' },
  { name: 'Luxemburgo', iso2: 'LU', dial: '+352' },
  { name: 'Macedonia del Norte', iso2: 'MK', dial: '+389' },
  { name: 'Madagascar', iso2: 'MG', dial: '+261' },
  { name: 'Malasia', iso2: 'MY', dial: '+60' },
  { name: 'Malaui', iso2: 'MW', dial: '+265' },
  { name: 'Maldivas', iso2: 'MV', dial: '+960' },
  { name: 'Malí', iso2: 'ML', dial: '+223' },
  { name: 'Malta', iso2: 'MT', dial: '+356' },
  { name: 'Marruecos', iso2: 'MA', dial: '+212' },
  { name: 'Mauricio', iso2: 'MU', dial: '+230' },
  { name: 'Mauritania', iso2: 'MR', dial: '+222' },
  { name: 'Micronesia', iso2: 'FM', dial: '+691' },
  { name: 'Moldavia', iso2: 'MD', dial: '+373' },
  { name: 'Mónaco', iso2: 'MC', dial: '+377' },
  { name: 'Mongolia', iso2: 'MN', dial: '+976' },
  { name: 'Montenegro', iso2: 'ME', dial: '+382' },
  { name: 'Mozambique', iso2: 'MZ', dial: '+258' },
  { name: 'Namibia', iso2: 'NA', dial: '+264' },
  { name: 'Nauru', iso2: 'NR', dial: '+674' },
  { name: 'Nepal', iso2: 'NP', dial: '+977' },
  { name: 'Nicaragua', iso2: 'NI', dial: '+505' },
  { name: 'Níger', iso2: 'NE', dial: '+227' },
  { name: 'Nigeria', iso2: 'NG', dial: '+234' },
  { name: 'Noruega', iso2: 'NO', dial: '+47' },
  { name: 'Nueva Zelanda', iso2: 'NZ', dial: '+64' },
  { name: 'Omán', iso2: 'OM', dial: '+968' },
  { name: 'Países Bajos', iso2: 'NL', dial: '+31' },
  { name: 'Pakistán', iso2: 'PK', dial: '+92' },
  { name: 'Palaos', iso2: 'PW', dial: '+680' },
  { name: 'Palestina', iso2: 'PS', dial: '+970' },
  { name: 'Panamá', iso2: 'PA', dial: '+507' },
  { name: 'Papúa Nueva Guinea', iso2: 'PG', dial: '+675' },
  { name: 'Paraguay', iso2: 'PY', dial: '+595' },
  { name: 'Perú', iso2: 'PE', dial: '+51' },
  { name: 'Polonia', iso2: 'PL', dial: '+48' },
  { name: 'Portugal', iso2: 'PT', dial: '+351' },
  { name: 'Reino Unido', iso2: 'GB', dial: '+44' },
  { name: 'República Centroafricana', iso2: 'CF', dial: '+236' },
  { name: 'República Checa', iso2: 'CZ', dial: '+420' },
  { name: 'República del Congo', iso2: 'CG', dial: '+242' },
  { name: 'República Democrática del Congo', iso2: 'CD', dial: '+243' },
  { name: 'República Dominicana', iso2: 'DO', dial: '+1809' },
  { name: 'Ruanda', iso2: 'RW', dial: '+250' },
  { name: 'Rumania', iso2: 'RO', dial: '+40' },
  { name: 'Rusia', iso2: 'RU', dial: '+7' },
  { name: 'Samoa', iso2: 'WS', dial: '+685' },
  { name: 'San Cristóbal y Nieves', iso2: 'KN', dial: '+1869' },
  { name: 'San Marino', iso2: 'SM', dial: '+378' },
  { name: 'San Vicente y las Granadinas', iso2: 'VC', dial: '+1784' },
  { name: 'Santa Lucía', iso2: 'LC', dial: '+1758' },
  { name: 'Santo Tomé y Príncipe', iso2: 'ST', dial: '+239' },
  { name: 'Senegal', iso2: 'SN', dial: '+221' },
  { name: 'Serbia', iso2: 'RS', dial: '+381' },
  { name: 'Seychelles', iso2: 'SC', dial: '+248' },
  { name: 'Sierra Leona', iso2: 'SL', dial: '+232' },
  { name: 'Singapur', iso2: 'SG', dial: '+65' },
  { name: 'Siria', iso2: 'SY', dial: '+963' },
  { name: 'Somalia', iso2: 'SO', dial: '+252' },
  { name: 'Sri Lanka', iso2: 'LK', dial: '+94' },
  { name: 'Sudáfrica', iso2: 'ZA', dial: '+27' },
  { name: 'Sudán', iso2: 'SD', dial: '+249' },
  { name: 'Sudán del Sur', iso2: 'SS', dial: '+211' },
  { name: 'Suecia', iso2: 'SE', dial: '+46' },
  { name: 'Suiza', iso2: 'CH', dial: '+41' },
  { name: 'Surinam', iso2: 'SR', dial: '+597' },
  { name: 'Tailandia', iso2: 'TH', dial: '+66' },
  { name: 'Tanzania', iso2: 'TZ', dial: '+255' },
  { name: 'Tayikistán', iso2: 'TJ', dial: '+992' },
  { name: 'Timor Oriental', iso2: 'TL', dial: '+670' },
  { name: 'Togo', iso2: 'TG', dial: '+228' },
  { name: 'Tonga', iso2: 'TO', dial: '+676' },
  { name: 'Trinidad y Tobago', iso2: 'TT', dial: '+1868' },
  { name: 'Túnez', iso2: 'TN', dial: '+216' },
  { name: 'Turkmenistán', iso2: 'TM', dial: '+993' },
  { name: 'Turquía', iso2: 'TR', dial: '+90' },
  { name: 'Tuvalu', iso2: 'TV', dial: '+688' },
  { name: 'Ucrania', iso2: 'UA', dial: '+380' },
  { name: 'Uganda', iso2: 'UG', dial: '+256' },
  { name: 'Uruguay', iso2: 'UY', dial: '+598' },
  { name: 'Uzbekistán', iso2: 'UZ', dial: '+998' },
  { name: 'Vanuatu', iso2: 'VU', dial: '+678' },
  { name: 'Venezuela', iso2: 'VE', dial: '+58' },
  { name: 'Vietnam', iso2: 'VN', dial: '+84' },
  { name: 'Yemen', iso2: 'YE', dial: '+967' },
  { name: 'Yibuti', iso2: 'DJ', dial: '+253' },
  { name: 'Zambia', iso2: 'ZM', dial: '+260' },
  { name: 'Zimbabue', iso2: 'ZW', dial: '+263' }
];

export function flagEmoji(iso2) {
  return String.fromCodePoint(...[...iso2.toUpperCase()].map(ch => 0x1F1E6 + ch.charCodeAt(0) - 65));
}
